org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

mod_id=gravityengine
mod_name=GravityEngine
mod_license=GNU GPL 3.0
mod_version=1.0.0-SNAPSHOT
mod_group_id=cc.sighs.gravityengine
mod_authors=
mod_description=Reusable gravity and body-attitude runtime API for Minecraft.

# Shared publishing IDs
# publish_curseforge_project_id=
# publish_modrinth_project_id=
